version: "3"

services:

  bitcoin:
    image: awazcognitum/gig-gossip-base:0.1

    container_name: giggossip_bitcoin
    restart: on-failure
    # command: ["sleep","infinity"]
    command: ["/work/bitcoin/src/bitcoind","-datadir=/work/locallnd/.bitcoin","-printtoconsole","-debug"]
    # command: bash -c "
    #     /work/bitcoin/src/bitcoind -datadir=/work/locallnd/.bitcoin
    #     && sleep infinity"
    ports:
      - 18332:18332
      - 28332:28332
      - 28333:28333
    volumes:
      - ./work/locallnd/.bitcoin:/work/locallnd/.bitcoin:Z
      # - ./work/locallnd/.giggossip:/work/locallnd/.giggossip:Z



  lightning_node_1:
    image: awazcognitum/gig-gossip-base:0.1

    container_name: giggossip_lightning_node_1
    restart: on-failure
    # command: /work/lnd/lnd-debug --lnddir=/work/locallnd/.lnd
    command: /work/lnd/lnd-debug --lnddir=/work/locallnd/.lnd --wallet-unlock-password-file=/work/locallnd/.secret/password.txt
    ports:
      - 9735:9735
      - 10009:10009
      - 8080:8080
    volumes:
      - ./work/locallnd/.lnd:/work/locallnd/.lnd:Z
      - ./work/locallnd/.secret:/work/locallnd/.secret:ro
    depends_on:
      - bitcoin



  lightning_node_2:
    image: awazcognitum/gig-gossip-base:0.1

    container_name: giggossip_lightning_node_2
    restart: on-failure
    # command: /work/lnd/lnd-debug --lnddir=/work/locallnd/.lnd
    command: /work/lnd/lnd-debug --lnddir=/work/locallnd/.lnd --wallet-unlock-password-file=/work/locallnd/.secret/password.txt
    ports:
      - 9734:9734
      - 11009:11009
      - 8180:8180
    volumes:
      - ./work/locallnd/.lnd2:/work/locallnd/.lnd:Z
      - ./work/locallnd/.secret:/work/locallnd/.secret:ro
    depends_on:
      - bitcoin



  lightning_node_3:
    image: awazcognitum/gig-gossip-base:0.1

    container_name: giggossip_lightning_node_3
    restart: on-failure
    # command: /work/lnd/lnd-debug --lnddir=/work/locallnd/.lnd
    command: /work/lnd/lnd-debug --lnddir=/work/locallnd/.lnd --wallet-unlock-password-file=/work/locallnd/.secret/password.txt
    ports:
      - 9736:9736
      - 11010:11010
      - 8181:8181
    volumes:
      - ./work/locallnd/.lnd3:/work/locallnd/.lnd:Z
      - ./work/locallnd/.secret:/work/locallnd/.secret:ro
    depends_on:
      - bitcoin



  nostr:
    image: python:3.10.13-alpine3.18

    container_name: giggossip_nostr
    restart: on-failure
    working_dir: /work/locallnd/.nostr_relay
    command: sh -c "pip install nostr-relay && nostr-relay -c config.yaml serve"
    ports:
      - 6969:6969
    volumes:
      - ./work/locallnd/.nostr_relay:/work/locallnd/.nostr_relay:Z




  # giggossip_api:
  #   image: giggossip_backend
  #   build: 
  #     context: ../.
  #     dockerfile: ./docker/docker_services_build/gigossip_backend_old.Dockerfile

  #   container_name: giggossip_api
  #   restart: on-failure
  #   # entrypoint: sh -c "dotnet ./NGigGossip4Nostr/GigLNDWalletAPI/bin/Debug/net7.0/GigLNDWalletAPI.dll --basedir=/work/locallnd/.giggossip/"
  #   ports:
  #     - 7101:7101
  #     - 7189:7189
  #   volumes:
  #     - ./work/locallnd/:/work/locallnd/:Z
  #   depends_on:
  #     - bitcoin
  #     - lightning_node_1
  #     - lightning_node_2
  #     - lightning_node_3


  wallet_api:
    image: giggossip_backend
    build: 
      context: ../.
      dockerfile: ./docker/docker_services_build/gigossip_backend.Dockerfile

    container_name: wallet_api
    restart: on-failure
    entrypoint: sh -c "dotnet ../gig-gossip-build/NGigGossip4Nostr/GigLNDWalletAPI/bin/Debug/net7.0/GigLNDWalletAPI.dll --basedir=/work/locallnd/.giggossip/"
    ports:
      - 7101:7101
    volumes:
      - ./work/locallnd/:/work/locallnd/:Z
    depends_on:
      - bitcoin
      - lightning_node_1
      - lightning_node_2
      - lightning_node_3


  settler_api:
    image: giggossip_backend
    build: 
      context: ../.
      dockerfile: ./docker/docker_services_build/gigossip_backend.Dockerfile

    container_name: settler_api
    restart: on-failure
    entrypoint: sh -c "dotnet ../gig-gossip-build/NGigGossip4Nostr/GigGossipSettlerAPI/bin/Debug/net7.0/GigGossipSettlerAPI.dll --basedir=/work/locallnd/.giggossip/"
    ports:
      - 7189:7189
    volumes:
      - ./work/locallnd/:/work/locallnd/:Z
    depends_on:
      - bitcoin
      - lightning_node_1
      - lightning_node_2
      - lightning_node_3
      - wallet_api


networks:
  default:
    name: giggossip
    driver: bridge
